import 'package:get/get.dart';

import 'app_constants.dart';

class LocalizedContent extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en': {
          AppConstants.APP_NAME: AppConstants.APP_NAME,
          AppConstants.APP_NAME_SUB: AppConstants.APP_NAME_SUB,
          AppConstants.INTRO_PAGE_1_HEADER_TEXT: AppConstants.INTRO_PAGE_1_HEADER_TEXT,
          AppConstants.INTRO_PAGE_1_SUB_HEADER_TEXT: AppConstants.INTRO_PAGE_1_SUB_HEADER_TEXT,
          AppConstants.INTRO_PAGE_2_HEADER_TEXT: AppConstants.INTRO_PAGE_2_HEADER_TEXT,
          AppConstants.INTRO_PAGE_2_SUB_HEADER_TEXT: AppConstants.INTRO_PAGE_2_SUB_HEADER_TEXT,
          AppConstants.INTRO_PAGE_3_HEADER_TEXT: AppConstants.INTRO_PAGE_3_HEADER_TEXT,
          AppConstants.INTRO_PAGE_3_SUB_HEADER_TEXT: AppConstants.INTRO_PAGE_3_SUB_HEADER_TEXT,
          AppConstants.INTRO_PAGE_DIRECT_BTN_TEXT: AppConstants.INTRO_PAGE_DIRECT_BTN_TEXT,
          AppConstants.INTRO_PAGE_DONE_BTN_TEXT: AppConstants.INTRO_PAGE_DONE_BTN_TEXT,
          AppConstants.LOADING_SCREEN_TIP_LABEL: AppConstants.LOADING_SCREEN_TIP_LABEL,
          AppConstants.LOADING_SCREEN_TIP: AppConstants.LOADING_SCREEN_TIP,
          AppConstants.SPEECH_TO_TEXT_HEADER_LABEL: AppConstants.SPEECH_TO_TEXT_HEADER_LABEL,
          AppConstants.TRANSLATION_HEADER_LABEL: AppConstants.TRANSLATION_HEADER_LABEL,
          AppConstants.SOURCE_DROPDOWN_LABEL: AppConstants.SOURCE_DROPDOWN_LABEL,
          AppConstants.TARGET_DROPDOWN_LABEL: AppConstants.TARGET_DROPDOWN_LABEL,
          AppConstants.DEFAULT_SELECT_DROPDOWN_LABEL: AppConstants.DEFAULT_SELECT_DROPDOWN_LABEL,
          AppConstants.INPUT_TEXT_LABEL: AppConstants.INPUT_TEXT_LABEL,
          AppConstants.OUTPUT_TEXT_LABEL: AppConstants.OUTPUT_TEXT_LABEL,
          AppConstants.RECORD_BUTTON_TEXT: AppConstants.RECORD_BUTTON_TEXT,
          AppConstants.STOP_BUTTON_TEXT: AppConstants.STOP_BUTTON_TEXT,
          AppConstants.UPDATE_BUTTON_TEXT: AppConstants.UPDATE_BUTTON_TEXT,
          AppConstants.UPDATING_BUTTON_TEXT: AppConstants.UPDATING_BUTTON_TEXT,
          AppConstants.PLAY_BUTTON_TEXT: AppConstants.PLAY_BUTTON_TEXT,
          AppConstants.PLAYING_BUTTON_TEXT: AppConstants.PLAYING_BUTTON_TEXT,
          AppConstants.MALE_TEXT_LABEL: AppConstants.MALE_TEXT_LABEL,
          AppConstants.FEMALE_TEXT_LABEL: AppConstants.FEMALE_TEXT_LABEL,
          AppConstants.ERROR_LABEL: AppConstants.ERROR_LABEL,
          AppConstants.SUCCESS_LABEL: AppConstants.SUCCESS_LABEL,
          AppConstants.HOME_SCREEN_CURRENT_STATUS_LABEL: AppConstants.HOME_SCREEN_CURRENT_STATUS_LABEL,
          AppConstants.INITIAL_CURRENT_STATUS_VALUE: AppConstants.INITIAL_CURRENT_STATUS_VALUE,
          AppConstants.USER_VOICE_RECORDING_STATUS_MSG: AppConstants.USER_VOICE_RECORDING_STATUS_MSG,
          AppConstants.SPEECH_RECG_REQ_STATUS_MSG: AppConstants.SPEECH_RECG_REQ_STATUS_MSG,
          AppConstants.SPEECH_RECG_SUCCESS_STATUS_MSG: AppConstants.SPEECH_RECG_SUCCESS_STATUS_MSG,
          AppConstants.SPEECH_RECG_FAIL_STATUS_MSG: AppConstants.SPEECH_RECG_FAIL_STATUS_MSG,
          AppConstants.SEND_TRANS_REQ_STATUS_MSG: AppConstants.SEND_TRANS_REQ_STATUS_MSG,
          AppConstants.TRANS_SUCCESS_STATUS_MSG: AppConstants.TRANS_SUCCESS_STATUS_MSG,
          AppConstants.TRANS_FAIL_STATUS_MSG: AppConstants.TRANS_FAIL_STATUS_MSG,
          AppConstants.SEND_TTS_REQ_STATUS_MSG: AppConstants.SEND_TTS_REQ_STATUS_MSG,
          AppConstants.TTS_SUCCESS_STATUS_MSG: AppConstants.TTS_SUCCESS_STATUS_MSG,
          AppConstants.TTS_FAIL_STATUS_MSG: AppConstants.TTS_FAIL_STATUS_MSG,
          AppConstants.OUTPUT_PLAYING_ERROR_MSG: AppConstants.OUTPUT_PLAYING_ERROR_MSG,
          AppConstants.SELECT_SOURCE_LANG_ERROR_MSG: AppConstants.SELECT_SOURCE_LANG_ERROR_MSG,
          AppConstants.SELECT_TARGET_LANG_ERROR_MSG: AppConstants.SELECT_TARGET_LANG_ERROR_MSG,
          AppConstants.TTS_NOT_GENERATED_ERROR_MSG: AppConstants.TTS_NOT_GENERATED_ERROR_MSG,
          AppConstants.NETWORK_REQS_IN_PROGRESS_ERROR_MSG: AppConstants.NETWORK_REQS_IN_PROGRESS_ERROR_MSG,
          AppConstants.MALE_FEMALE_TTS_UNAVAILABLE: AppConstants.MALE_FEMALE_TTS_UNAVAILABLE,
          AppConstants.RECORDING_IN_PROGRESS: AppConstants.RECORDING_IN_PROGRESS,
          AppConstants.CLIPBOARD_TEXT_COPY_SUCCESS: AppConstants.CLIPBOARD_TEXT_COPY_SUCCESS,
          AppConstants.DEVELOPED_BY_LABEL: AppConstants.DEVELOPED_BY_LABEL,
          AppConstants.DEVELOPED_BY: AppConstants.DEVELOPED_BY,
          AppConstants.DEVELOPED_BY_ORG_LABEL: AppConstants.DEVELOPED_BY_ORG_LABEL,
          AppConstants.DEVELOPED_BY_ORG_CONTENT: AppConstants.DEVELOPED_BY_ORG_CONTENT,
          AppConstants.APPLICATION_VERSION_LABEL: AppConstants.APPLICATION_VERSION_LABEL,
          AppConstants.APPLICATION_VERSION: AppConstants.APPLICATION_VERSION,
        },
        'hi': {
          AppConstants.APP_NAME: 'भाषावर्स',
          AppConstants.APP_NAME_SUB: 'संचालित करने वाला',
          AppConstants.INTRO_PAGE_1_HEADER_TEXT: 'भाषा से भाषा का अनुवाद',
          AppConstants.INTRO_PAGE_1_SUB_HEADER_TEXT: 'यहाँ एक भारतीय भाषा की आवाज़ को दूसरी भारतीय भाषा में बदलें',
          AppConstants.INTRO_PAGE_2_HEADER_TEXT: 'भाषा की पहचान',
          AppConstants.INTRO_PAGE_2_SUB_HEADER_TEXT: 'स्वचालित तरीके से भाषा की पहचान और वाक्य में परिवर्तन',
          AppConstants.INTRO_PAGE_3_HEADER_TEXT: 'भाषा का अनुवाद',
          AppConstants.INTRO_PAGE_3_SUB_HEADER_TEXT: 'भारीतय भाषा के एक वाक्य का दूसरी भारतीय भाषा में अनुवाद',
          AppConstants.INTRO_PAGE_DIRECT_BTN_TEXT: 'आइये सीधा अनुवाद करें',
          AppConstants.INTRO_PAGE_DONE_BTN_TEXT: 'आगे बढ़ें',
          AppConstants.LOADING_SCREEN_TIP_LABEL: 'टिप्पणी:',
          AppConstants.LOADING_SCREEN_TIP: ' वाक्य को कॉपी करने के लिए उस पर क्लिक करें',
          AppConstants.SPEECH_TO_TEXT_HEADER_LABEL: 'आवाज़ का वाक्य में रूपांतरण',
          AppConstants.TRANSLATION_HEADER_LABEL: 'अनुवाद',
          AppConstants.SOURCE_DROPDOWN_LABEL: 'इस भाषा से',
          AppConstants.TARGET_DROPDOWN_LABEL: 'इस भाषा में',
          AppConstants.DEFAULT_SELECT_DROPDOWN_LABEL: 'भाषा चुनें',
          AppConstants.INPUT_TEXT_LABEL: 'आवाज़ रिकॉर्ड करें',
          AppConstants.OUTPUT_TEXT_LABEL: 'अनुवाद की गयी आवाज़',
          AppConstants.RECORD_BUTTON_TEXT: 'रिकॉर्ड करो',
          AppConstants.STOP_BUTTON_TEXT: 'रोक दो',
          AppConstants.UPDATE_BUTTON_TEXT: 'अपडेट करो',
          AppConstants.UPDATING_BUTTON_TEXT: 'अपडेट कर रहे हैं',
          AppConstants.PLAY_BUTTON_TEXT: 'आवाज़ सुनें',
          AppConstants.PLAYING_BUTTON_TEXT: 'आवाज़ सुनाई जा रही है',
          AppConstants.MALE_TEXT_LABEL: 'पुरुष',
          AppConstants.FEMALE_TEXT_LABEL: 'महिला',
          AppConstants.ERROR_LABEL: 'गलती',
          AppConstants.SUCCESS_LABEL: 'सफलता',
          AppConstants.HOME_SCREEN_CURRENT_STATUS_LABEL: 'वर्तमान स्थिति : ',
          AppConstants.INITIAL_CURRENT_STATUS_VALUE: 'एक भाषा की आवाज़ को दूसरी भाषा में बदलना आरम्भ करें',
          AppConstants.USER_VOICE_RECORDING_STATUS_MSG: 'आपकी आवाज़ रिकॉर्ड की जा रही है...',
          AppConstants.SPEECH_RECG_REQ_STATUS_MSG: '%replaceContent% भाषा की पहचान की जा रही है',
          AppConstants.SPEECH_RECG_SUCCESS_STATUS_MSG: '%replaceContent% भाषा की पहचान सफलतापूर्वक कर ली गयी है',
          AppConstants.SPEECH_RECG_FAIL_STATUS_MSG: '%replaceContent% भाषा की पहचान विफल हो गई है',
          AppConstants.SEND_TRANS_REQ_STATUS_MSG: '%replaceContent1% भाषा का %replaceContent2% भाषा में अनुवाद किआ जा रहा है',
          AppConstants.TRANS_SUCCESS_STATUS_MSG: '%replaceContent1% भाषा का %replaceContent2% भाषा में अनुवाद सफलतापूर्वक कर लिया गया है',
          AppConstants.TRANS_FAIL_STATUS_MSG: '%replaceContent1% भाषा का %replaceContent2% भाषा में अनुवाद विफल हो गया है',
          AppConstants.SEND_TTS_REQ_STATUS_MSG: '%replaceContent% भाषा में आवाज़ उत्पन्न की जा रही है',
          AppConstants.TTS_SUCCESS_STATUS_MSG: '%replaceContent% भाषा में आवाज़ उत्पन्न कर ली गयी है',
          AppConstants.TTS_FAIL_STATUS_MSG: '%replaceContent% भाषा में आवाज़ उत्पन्न करना विफल हो गया है',
          AppConstants.OUTPUT_PLAYING_ERROR_MSG: 'अभी एक भाषा की आवाज़ सुनाई जा रही है',
          AppConstants.SELECT_SOURCE_LANG_ERROR_MSG: 'कृपया जिस भाषा को बदलना है, पहले वो भाषा चुनें',
          AppConstants.SELECT_TARGET_LANG_ERROR_MSG: 'कृपया जिस भाषा में बदलना है, पहले वो भाषा चुनें',
          AppConstants.TTS_NOT_GENERATED_ERROR_MSG: 'कृपया पहले अपनी भाषा में आवाज़ देकर दूसरी भाषा में आवाज़ उत्पन्न करें',
          AppConstants.NETWORK_REQS_IN_PROGRESS_ERROR_MSG: 'अभी आपकी पुरानी आवाज़ का अनुवाद और नयी भाषा की आवाज़ उत्पन्न की जा रही है',
          AppConstants.MALE_FEMALE_TTS_UNAVAILABLE: 'अभी %replaceContent% की आवाज़ में ये भाषा उपलब्ध नहीं है',
          AppConstants.RECORDING_IN_PROGRESS: 'अभी आपकी आवाज़ रिकॉर्ड की जा रही है',
          AppConstants.CLIPBOARD_TEXT_COPY_SUCCESS: 'आपके द्वारा टच किआ गया वाक्य अब कॉपी हो गया है',
        }
      };
}
